app/camera/__init__.py
from flask import Blueprint

cam = Blueprint('cam', __name__)

from . import views

app/camera/views.py
from flask import Flask, render_template, Response, request, redirect, url_for, send_file
# from ..url_for2 import url_for2

from flask_login import login_required, current_user
import cv2
import datetime, time
import os, sys
import numpy as np
from threading import Thread
from . import cam
from itertools import count
import glob, re

gpio_ok = True

try:
    import RPi.GPIO as GPIO
except:
    gpio_ok = False

if gpio_ok:
    print('GPIO support OK!')
else:
    print('WARNING: GPIO in failsafe mode')

capture = False
grey = False
neg = False
camera_on = False
rec = False

verbose = True

# LEDs state
leds_status = [False, False, False, False]
led_labels = { 'led1' : 0, 'led2' : 1, 'led3' : 2, 'led4' : 3}

gpio_led1 = 18
gpio_led2 = 23
gpio_led3 = 24
gpio_led4 = 25
gpio_pins = [gpio_led1, gpio_led2, gpio_led3, gpio_led4]

camera_device = 0

if gpio_ok:
    # Set up GPIO pins
    GPIO.setmode(GPIO.BCM)
    GPIO.setwarnings(False)
    for pin in gpio_pins:
        GPIO.setup(pin, GPIO.OUT)
        GPIO.output(pin,0)

def led_set(led, on):
    if verbose:
        print(f'led_set: LED{led + 1} ' + ('ON' if on else 'OFF'))
    leds_status[led] = True if on else False
    if gpio_ok:
        GPIO.output(gpio_pins[led], on)

# not used anywhere
def turn_leds_off():
    for led in range(4):
        led_set(led, 0)

# not used anywhere
def turn_leds_on():
    for led in range(4):
        led_set(led, leds_status[led])


#make shots directory to save pics
try:
    os.mkdir('./shots')
except OSError as error:
    pass

#make videos directory to save videos
try:
    os.mkdir('./videos')
except OSError as error:
    pass

def cam_record():
    global rec, rec_frame, rec_status, camera, camera_on
    rec = True

    print('Openning VideoCapture inside the thread')
    if not camera_on:
        camera = cv2.VideoCapture(camera_device)

    # Check if camera opened successfully
    while not camera.isOpened():
        print(f'Unable to read camera feed camera={camera}')
        if not rec:
            # cv2.destroyAllWindows()
            return

    # get a valid frame to determine properties
    for i in count(1):
        print(f'Trying to read (i={i})...')
        ret, _ = camera.read()
        if ret:
            break
        if not rec:
            return

    # Default resolutions of the frame are obtained.The default resolutions are system dependent.
    # We convert the resolutions from float to integer.
    frame_width = int(camera.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(camera.get(cv2.CAP_PROP_FRAME_HEIGHT))
    frame_rate = int(camera.get(cv2.CAP_PROP_FPS))
    print(f'frame_rate={frame_rate}, frame_width={frame_width}, frame_height={frame_height}')
    # Define the codec and create VideoWriter object. The output is stored in 'outpy.avi' file.
    now = datetime.datetime.now()
    out = cv2.VideoWriter('videos/vid_{}.avi'.format(str(now).replace(":",'')), cv2.VideoWriter_fourcc('M','J','P','G'), 20, (frame_width, frame_height))

    while True:
      rec_status, rec_frame = camera.read()
      if rec_status:
        # Write the frame into the file 'output.avi'
        out.write(rec_frame)
        if not rec:
          break
    # When everything is done, release the video capture and video write objects
    if not camera_on:
        camera.release()
    out.release()

def gen_frames():  # generate frame by frame from camera
    global out, capture, rec_frame
    while rec or camera_on:
        if not rec:
            success, frame = camera.read()
            if success:
                if grey:
                    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                if neg:
                    frame = cv2.bitwise_not(frame)
                if capture:
                    capture = False
                    now = datetime.datetime.now()
                    p = os.path.sep.join(['shots', "shot_{}.png".format(str(now).replace(":",''))])
                    cv2.imwrite(p, frame)
                try:
                    _, buffer = cv2.imencode('.jpg', cv2.flip(frame,1))
                    frame = buffer.tobytes()
                    yield (b'--frame\r\n'
                           b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
                except Exception as e:
                    pass
        else:
            try:
                _, buffer = cv2.imencode('.jpg', rec_frame)
                frame = buffer.tobytes()
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
            except Exception as e:
                pass

@cam.route('/camera')
@login_required
def index():
    global camera_on, neg, grey, rec, leds_status
    return render_template('camera/camera.html', camera_on = camera_on, neg = neg, grey = grey, rec = rec, led1 = leds_status[0], led2 = leds_status[1], led3 = leds_status[2], led4 = leds_status[3])

@cam.route('/video_feed')
@login_required
def video_feed():
    if camera_on or rec:
        return Response(gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')
    else:
        return redirect(url_for('.index'))

@cam.route('/cam_requests',methods=['POST','GET'])
@login_required
def tasks():
    global camera_on,camera, capture, grey, neg, rec
    print('Entering cam_requests')
    if request.method == 'POST':
        if request.form.get('click'):
            capture = True
        elif  request.form.get('color'):
            grey = False
        elif  request.form.get('grey'):
            grey = True
        elif  request.form.get('pos'):
            neg = False
        elif  request.form.get('neg'):
            neg = True
        elif  request.form.get('start'):
            if not camera_on and not rec:
                camera = cv2.VideoCapture(camera_device)
            camera_on = True
        elif  request.form.get('stop'):
            if camera_on and not rec:
                camera.release()
            camera_on = False
        elif request.form.get('rec_start'):
            if not rec:
                #Start new thread for recording the video
                th = Thread(target = cam_record)
                th.start()
                time.sleep(1)
        elif request.form.get('rec_stop'):
            if rec:
                rec = False
                time.sleep(1)
    print('Leaving cam_requests')
    return redirect(url_for('.index'))

@cam.route('/tabela',methods=['POST','GET'])
def tabela():
    return render_template('camera/tabela.html')

@cam.route('/files',methods=['POST','GET'])
@login_required
def files():
    fns = glob.glob('videos/*.avi')
    if fns != []:
        fns = list(map(lambda x: x.lstrip('videos').lstrip('/'), fns))
        dates = list(map(lambda x: re.search(r'[0-9]+-[0-9]+-[0-9]+', x).group(0), fns))
        times = list(map(lambda x: re.search(r' [0-9]+\.[0-9]+.avi$', x).group(0).lstrip().rstrip('.avi'), fns))
        d = list(map(lambda x, y, z: list([x, y, z]), fns, dates, times))
    else:
        d = []
    return render_template('camera/files.html', data = d)

@cam.route('/file_action',methods=['POST'])
@login_required
def file_action():
    if request.form.get('download'):
        print('download')
        fn = 'vid_{} {}.avi'.format(request.form.get('date'), request.form.get('time'))
        print(f'fn={fn} getenv("PWD")={os.getenv("PWD")}')
        try:
            return send_file('../videos/' + fn)
        except Exception as e:
            print(str(e))
    if request.form.get('erase'):
        fn = 'videos/vid_{} {}.avi'.format(request.form.get('date'), request.form.get('time'))
        print('erase')
        print(f'fn={fn}')
        os.unlink(fn)
    return redirect(url_for('cam.files'))

@cam.route('/set_led/<string:led>/<int:on>', methods=['GET'])
@login_required
def set_led(led, on):
    n = led_labels[led]
    led_set(n, on)
    return str(on)

@cam.route('/get_led/<string:led>', methods=['GET'])
@login_required
def get_led(led):
    n = led_labels[led]
    return str('1' if leds_status[led_labels[led]] else '0')

@cam.route('/set_leds', methods = ['POST'])
@login_required
def set_leds():
    for led in led_labels:
        if request.form.get(led):
            led_set(led_labels[led], 1)
        else:
            led_set(led_labels[led], 0)
    return redirect(url_for('cam.index'))

app/templates/camera/camera.html
{% extends "base.html" %}

{% block title %}Macbee{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Camera</h1>
</div>

    <div class="container">
        <div class="row">
            <ul>
                <li> Camera: {{ "ON" if camera_on else "OFF" }} </li>
                <li> Recording {{ "ON" if rec else "OFF" }} </li>
            </ul>
        </div>
        <div class="row">
            <p><form method="post" action="/set_leds">
                <table>
                    <tr>
                        <td>LEDs:</td>
                        <td>&nbsp;
                            <input type="checkbox" id="led1" name="led1" {% if led1 %} checked {% endif %}>
                            <label for="led1">LED1</label></td>
                        <td>&nbsp;
                            <input type="checkbox" id="led2" name="led2" {% if led2 %} checked {% endif %}>
                            <label for="led2">LED2</label></td>
                        <td>&nbsp;
                            <input type="checkbox" id="led3" name="led3" {% if led3 %} checked {% endif %}> 
                            <label for="led3">LED3</label></td>
                        <td>&nbsp;
                            <input type="checkbox" id="led4" name="led4" {% if led4 %} checked {% endif %}>
                            <label for="led4">LED4</label></td>
                        <td>&nbsp;
                            <input type="submit" name="set_leds" value="Set LEDs"></td>
                    </tr>
                </table>
            </form>
            </p>
                <form method="post" action="{{ url_for('cam.tasks') }}">
                    <p>
                        {% if camera_on%}
			                  <input type="submit" value="Stop View" name="stop" />
                        {% else %}
                        <input type="submit" value="View Camera" name="start" />
                        {% endif %}

                        {% if rec %}

			                  <input type="submit" value="Stop Recording" name="rec_stop" />

                        {% else %}

			                  <input type="submit" value="Capture" name="click"/>

                        {% if grey %}
			                  <input type="submit" value="Color" name="color" />
                        {% else %}
			                  <input type="submit" value="Grey" name="grey" />
                        {% endif %}

                        {% if neg %}
			                  <input type="submit" value="Positive" name="pos" />
                        {% else %}
			                  <input type="submit" value="Negative" name="neg" />
                        {% endif %}

			                  <input type="submit" value="Start Recording" name="rec_start" />
                        {% endif %}
                    </p>
			          </form>
                <br>
                {% if camera_on %}
                <img src="{{ url_for('cam.video_feed') }}" height="80%">
                {% else %}
                <img src="{{ current_user.gravatar() }}">
                {% endif %}
        </div>
    </div>
    <script src="{{url_for('static', filename='led_check.js')}}"></script>
    {% endblock %}

app/templates/camera/files.html
{% extends "base.html" %}

{% block title %}Macbee{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Arquivos salvos no SDCard</h1>
</div>

<table>
    {% for r, d, tm in data %}
    <tr>
        <td>{{ r }}</td>
        <td><form method="POST" action="file_action"><input type="hidden"  name="date" value="{{ d }}"><input type="hidden" name="time" value="{{ tm }}"><input type="Submit" name="download" value="Baixar"><input type="Submit" name="erase" value="Apagar"></form></td>
    </tr>
    {% endfor %}
</ul>

{% endblock %}

app/templates/camera/tabela.html
{% extends "base.html" %}

{% block title %}Macbee{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Tabela dos Valores do Campo Magnético</h1>
</div>

<table class="cssTable" border="1">
    <tr>
        <th> Tensão no Knob (V)</th>
        <th> Tensão eficaz verdadeira (V)<a href="#note1">[1]</a> </th>
        <th> Corrente eficaz (A)</th>
        <th> Densidade de Fluxo Magnético (mT)<a href="#note2">[2]</a> </th>
    </tr>
    <tr>
        <td> 25 </td>
        <td> 27 </td>
        <td> 0,373 </td>
        <td> 0,95 </td>
    </tr>
    <tr>
        <td> 50 </td>
        <td> 48,6 </td>
        <td> 0,65 </td>
        <td> 1,66 </td>
    </tr>
    <tr>
        <td> 75 </td>
        <td> 69,8 </td>
        <td> 0,97 </td>
        <td> 2,48 </td>
    </tr>
    <tr>
        <td> 100 </td>
        <td> 90,4 </td>
        <td> 1,28 </td>
        <td> 3,27 </td>
    </tr>
    <tr>
        <td> 125 </td>
        <td> 113,2 </td>
        <td> 1,62 </td>
        <td> 4,14 </td>
    </tr>
    <tr>
        <td> 150 </td>
        <td> 139,2 </td>
        <td> 1,98 </td>
        <td> 5,06 </td>
    </tr>
    <tr>
        <td> 175 </td>
        <td> 166,9 </td>
        <td> 2,39 </td>
        <td> 6,10 </td>
    </tr>
    <tr>
        <td> 200 </td>
        <td> 197 </td>
        <td> 2,82 </td>
        <td> 7,20 </td>
    </tr>
    <tr>
        <td> 225 </td>
        <td> 224,7 </td>
        <td> 3,24 </td>
        <td> 8,27 </td>
    </tr>
    <tr>
        <td> MAX </td>
        <td> 243,1 </td>
        <td> 3,51 </td>
        <td> 8,96 </td>
    </tr>
</table>

<p id="note1"> [1] Valores medidos com voltímetro na saída do VARIAC, para uma entrada de tensão de 220V (medida com o voltímetro).</p>
<p id="note2"> [2] Valor máximo da densidade de fluxo magnético na trajetória de campo mínimo.</p>

<h2>Distribuição da Densidade de Fluxo Magnético</h2>

<p>A seguir, a distribuição da Densidade de fluxo magnético para uma corrente com valor eficaz de 2,82A.</p>

<p> Os valores são proporcionais à corrente da tabela acima. Por exemplo, para uma corrente de 1,28A, posição 100V para uma rede de 220V, tem-se uma densidade de campo de 7,2 * 1,28 / 2,82 = 3,27mT, na trajetória de menor campo da figura.</p>

<img src="{{ url_for('static', filename = 'Field-w-4A.svg') }}" alt="Distribuição da Densidade de Fluxo" width="1000">

<h2> Esquema de Ligações</h2>

<p> A figura abaixo mostra o esquema de ligações das bobinas. As duas bibinas devem ser <b> separadas por uma distância de 20cm</b>, que foi a condição de projeto. <b>Os terminais de uma mesma cor devem ser sempre colocados para o mesmo lado</b>, caso contrário, os fluxos ficarão em oposição e o campo será muito mais baixo, anulando-se no centro. <b>Um terminal do VARIAC deve ser conectado a uma cor</b> (por exemplo, vermelho) e <b>o outro terminal, à outra cor </b>(por exemplo, preto). Os terminais restantes devem ser conectados ao VARIAC.

<img src="{{ url_for('static', filename = 'Ligacoes.svg') }}" alt="Esquema de Ligações" width="1000">

{% endblock %}
 